In [ ]:
from google.colab import files
upload = files.upload()

Saving Purchase_Fraud_Data.csv to Purchase_Fraud_Data.csv


In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("Purchase_Fraud_Data.csv")
data.shape

(151112, 12)

In [ ]:
data.head()

user_id          signup_time  ...         category        dob
0    22058  2015-02-24 22:55:49  ...  home_essentials  22-2-1976
1   333320  2015-06-07 20:39:50  ...         apparels   2-1-1962
2     1359  2015-01-01 18:52:44  ...      electronics   5-3-1962
3   150084  2015-04-28 21:13:25  ...      health_care   3-7-1974
4   221365  2015-07-21 07:09:52  ...  home_essentials  25-8-1970

[5 rows x 12 columns]

In [ ]:
data.describe(include="all")

user_id          signup_time  ...     category        dob
count   151112.000000               151112  ...       151112     146188
unique            NaN               151112  ...            5      13745
top               NaN  2015-02-24 22:55:49  ...  electronics  24-7-1982
freq              NaN                    1  ...        32056         37
mean    200171.040970                  NaN  ...          NaN        NaN
std     115369.285024                  NaN  ...          NaN        NaN
min          2.000000                  NaN  ...          NaN        NaN
25%     100642.500000                  NaN  ...          NaN        NaN
50%     199958.000000                  NaN  ...          NaN        NaN
75%     300054.000000                  NaN  ...          NaN        NaN
max     400000.000000                  NaN  ...          NaN        NaN

[11 rows x 12 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151112 entries, 0 to 151111
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   user_id         151112 non-null  int64  
 1   signup_time     151112 non-null  object 
 2   purchase_time   151112 non-null  object 
 3   purchase_value  151112 non-null  int64  
 4   device_id       151112 non-null  object 
 5   source          151112 non-null  object 
 6   browser         151112 non-null  object 
 7   sex             146185 non-null  object 
 8   ip_address      151112 non-null  float64
 9   class           151112 non-null  int64  
 10  category        151112 non-null  object 
 11  dob             146188 non-null  object 
dtypes: float64(1), int64(3), object(8)
memory usage: 13.8+ MB


In [ ]:
data.isna().sum()

user_id              0
signup_time          0
purchase_time        0
purchase_value       0
device_id            0
source               0
browser              0
sex               4927
ip_address           0
class                0
category             0
dob               4924
dtype: int64

USER ID

In [ ]:
len(data.user_id.unique())  

151112

In [ ]:
data.drop(columns=["user_id"],inplace=True)

Signup Time : Date & Time at which the customer signup in the platform

In [ ]:
data["signup_time"] = pd.to_datetime(data["signup_time"])

In [ ]:
data["signup_time_year"] = data["signup_time"].dt.year
data["signup_time_month"] = data["signup_time"].dt.month
data["signup_time_day"] = data["signup_time"].dt.day
data["signup_time_week"] = data["signup_time"].dt.dayofweek
data["signup_time_hour"] = data["signup_time"].dt.hour
data.drop(columns = ["signup_time"],inplace=True)

Purchase Time:  The latest purchase date & time from a customer

In [ ]:
data["purchase_time"] = pd.to_datetime(data["purchase_time"])

In [ ]:
data["purchase_time_year"] = data["purchase_time"].dt.year
data["purchase_time_month"] = data["purchase_time"].dt.month
data["purchase_time_day"] = data["purchase_time"].dt.day
data["purchase_time_week"] = data["purchase_time"].dt.dayofweek
data["purchase_time_hour"] = data["purchase_time"].dt.hour
data.drop(columns = ["purchase_time"],inplace=True)

Purchase Value : Total purchase amount

In [ ]:
from sklearn.preprocessing import StandardScaler
SS = StandardScaler()
SS.fit(data[["purchase_value"]])
data.purchase_value = SS.transform(data[["purchase_value"]])
data.head()

purchase_value      device_id  ... purchase_time_week purchase_time_hour
0        0.517164  QVPSPJUOCKZAR  ...                  5                  2
1        1.607844  EOGFQPIZPYXFZ  ...                  0                  1
2        0.237423  YSSKYOSJHPPLJ  ...                  3                 18
3       -0.240820  ATGTXKYKUDUQN  ...                  0                 13
4       -0.192947  NAUITBZFJKHWW  ...                  2                 18

[5 rows x 19 columns]

Device ID : Unique device ID from which purchase was done

In [ ]:
data.device_id.unique

<bound method Series.unique of 0         QVPSPJUOCKZAR
1         EOGFQPIZPYXFZ
2         YSSKYOSJHPPLJ
3         ATGTXKYKUDUQN
4         NAUITBZFJKHWW
              ...      
151107    XPSKTWGPWINLR
151108    LYSFABUCPCGBA
151109    MEQHCSJUBRBFE
151110    CMCXFGRHYSTVJ
151111    ZINIADFCLHYPG
Name: device_id, Length: 151112, dtype: object>

In [ ]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
LE.fit(data[["device_id"]])
data.device_id = LE.transform(data[["device_id"]])
SS.fit(data[["device_id"]])
data.device_id = SS.transform(data[["device_id"]])
data.head()

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


purchase_value  device_id  ... purchase_time_week purchase_time_hour
0        0.517164   0.508156  ...                  5                  2
1        1.607844  -1.127751  ...                  0                  1
2        0.237423   1.563005  ...                  3                 18
3       -0.240820  -1.632585  ...                  0                 13
4       -0.192947  -0.005644  ...                  2                 18

[5 rows x 19 columns]

Category : Type of product purchased

In [ ]:
data.category.value_counts(normalize = True)

electronics        0.212134
cosmetics          0.198131
apparels           0.197006
health_care        0.196470
home_essentials    0.196258
Name: category, dtype: float64

In [ ]:
temp = pd.get_dummies(data["category"],prefix="Category")
#temp.head()
data = pd.concat([data,temp],axis=1)
data = data.drop(columns=["category"])
data.head()

purchase_value  device_id  ... Category_health_care Category_home_essentials
0        0.517164   0.508156  ...                    0                        1
1        1.607844  -1.127751  ...                    0                        0
2        0.237423   1.563005  ...                    0                        0
3       -0.240820  -1.632585  ...                    1                        0
4       -0.192947  -0.005644  ...                    0                        1

[5 rows x 23 columns]

Source : Medium through which customers reached the platform

In [ ]:
data.source.value_counts(normalize = True)

SEO       0.401126
Ads       0.396269
Direct    0.202605
Name: source, dtype: float64

In [ ]:
temp = pd.get_dummies(data["source"],prefix="Source")
#temp.head()
data = pd.concat([data,temp],axis=1)
data = data.drop(columns=["source"])
data.head()

purchase_value  device_id browser  ... Source_Ads  Source_Direct  Source_SEO
0        0.517164   0.508156  Chrome  ...          0              0           1
1        1.607844  -1.127751  Chrome  ...          1              0           0
2        0.237423   1.563005   Opera  ...          0              0           1
3       -0.240820  -1.632585  Safari  ...          0              0           1
4       -0.192947  -0.005644  Safari  ...          1              0           0

[5 rows x 25 columns]

Browser: Browser used while purchasing

In [ ]:
data.browser.value_counts(normalize = True)

Chrome     0.406533
IE         0.243045
Safari     0.163237
FireFox    0.162859
Opera      0.024326
Name: browser, dtype: float64

In [ ]:
temp = pd.get_dummies(data["browser"],prefix="Browser")
#temp.head()
data = pd.concat([data,temp],axis=1)
data = data.drop(columns=["browser"])
data.head()

purchase_value  device_id sex  ...  Browser_IE  Browser_Opera Browser_Safari
0        0.517164   0.508156   M  ...           0              0              0
1        1.607844  -1.127751   F  ...           0              0              0
2        0.237423   1.563005   M  ...           0              1              0
3       -0.240820  -1.632585   M  ...           0              0              1
4       -0.192947  -0.005644   M  ...           0              0              1

[5 rows x 29 columns]

IP Address

In [ ]:
data.ip_address.value_counts(normalize = True)

1.502818e+09    0.000132
5.760609e+08    0.000132
3.874758e+09    0.000132
2.050964e+09    0.000132
1.800550e+09    0.000126
                  ...   
2.099897e+09    0.000007
1.856830e+09    0.000007
1.637622e+09    0.000007
6.246035e+08    0.000007
4.103825e+09    0.000007
Name: ip_address, Length: 143512, dtype: float64

In [ ]:
SS.fit(data[["ip_address"]])
data.ip_address = SS.transform(data[["ip_address"]])
data.head()

purchase_value  device_id sex  ...  Browser_IE  Browser_Opera Browser_Safari
0        0.517164   0.508156   M  ...           0              0              0
1        1.607844  -1.127751   F  ...           0              0              0
2        0.237423   1.563005   M  ...           0              1              0
3       -0.240820  -1.632585   M  ...           0              0              1
4       -0.192947  -0.005644   M  ...           0              0              1

[5 rows x 29 columns]

sex  

In [ ]:
data.sex.value_counts()

M    85445
F    60740
Name: sex, dtype: int64

In [ ]:
data["sex"] = data.sex.fillna("Unknown")

In [ ]:
temp = pd.get_dummies(data["sex"],prefix="Sex")
#temp.head()
data = pd.concat([data,temp],axis=1)
data = data.drop(columns=["sex"])
data.head()

purchase_value  device_id  ip_address  ...  Sex_F Sex_M  Sex_Unknown
0        0.517164   0.508156   -1.136880  ...      0     1            0
1        1.607844  -1.127751   -1.443207  ...      1     0            0
2        0.237423   1.563005    0.375916  ...      0     1            0
3       -0.240820  -1.632585    1.352348  ...      0     1            0
4       -0.192947  -0.005644   -1.390927  ...      0     1            0

[5 rows x 31 columns]

DOB

In [ ]:
data[["dob"]].describe()

dob
count      146188
unique      13745
top     24-7-1982
freq           37

In [ ]:
Mode_DOB = data[["dob"]].mode()
print(Mode_DOB)

         dob
0  24-7-1982


In [ ]:
data["dob"] = data.dob.fillna("24-7-1982")

In [ ]:
data["dob"] = pd.to_datetime(data["dob"])

In [ ]:
data["dob"] = data["dob"].dt.year

In [ ]:
data["Age_at_purchase"] = data["purchase_time_year"] - data["dob"]

In [ ]:
data["Age_at_purchase"].describe()

count    151112.000000
mean         33.849013
std           9.439681
min          18.000000
25%          27.000000
50%          33.000000
75%          39.000000
max          76.000000
Name: Age_at_purchase, dtype: float64

In [ ]:
data = data.drop(columns=["dob"])
data.head()

purchase_value  device_id  ip_address  ...  Sex_M  Sex_Unknown  Age_at_purchase
0        0.517164   0.508156   -1.136880  ...      1            0               39
1        1.607844  -1.127751   -1.443207  ...      0            0               53
2        0.237423   1.563005    0.375916  ...      1            0               53
3       -0.240820  -1.632585    1.352348  ...      1            0               41
4       -0.192947  -0.005644   -1.390927  ...      1            0               45

[5 rows x 31 columns]

In [ ]:
SS.fit(data[["Age_at_purchase"]])
data.Age_at_purchase = SS.transform(data[["Age_at_purchase"]])
data.head()

purchase_value  device_id  ip_address  ...  Sex_M  Sex_Unknown  Age_at_purchase
0        0.517164   0.508156   -1.136880  ...      1            0         0.545676
1        1.607844  -1.127751   -1.443207  ...      0            0         2.028782
2        0.237423   1.563005    0.375916  ...      1            0         2.028782
3       -0.240820  -1.632585    1.352348  ...      1            0         0.757548
4       -0.192947  -0.005644   -1.390927  ...      1            0         1.181292

[5 rows x 31 columns]

In [ ]:
X = data.drop(columns=["class"])
y = data[["class"]]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=55,stratify=y)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((113334, 30), (37778, 30), (113334, 1), (37778, 1))

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion='entropy')
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
print("Accuracy : ",accuracy_score(y_test,y_pred))

Accuracy :  0.9286357139075653


In [ ]:
clf = DecisionTreeClassifier(criterion='gini')
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
print("Accuracy : ",accuracy_score(y_test,y_pred))

Accuracy :  0.9269680766583726


In [ ]:
confusion_matrix(y_test,y_pred)


array([[32619,  1621],
       [ 1138,  2400]])

In [ ]:
from sklearn.linear_model import LogisticRegression
M1 = LogisticRegression()
M1.fit(X_train,y_train)
y_pred1 = M1.predict(X_test)
print("Accuracy : ",accuracy_score(y_test,y_pred1))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy :  0.9366033140981523


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [ ]:
from sklearn import metrics
from sklearn.metrics import classification_report,r2_score
import numpy as np
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred1))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred1))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred1)))
print('R^2 score is:', r2_score(y_test, y_pred1))
print("Accuracy : ",metrics.accuracy_score(y_test,y_pred1))
print(classification_report(y_test,y_pred1))

Mean Absolute Error: 0.06339668590184763
Mean Squared Error: 0.06339668590184763
Root Mean Squared Error: 0.2517869851716876
R^2 score is: 0.2531164479905751
Accuracy :  0.9366033140981523
              precision    recall  f1-score   support

           0       0.94      1.00      0.97     34240
           1       0.89      0.37      0.52      3538

    accuracy                           0.94     37778
   macro avg       0.92      0.68      0.74     37778
weighted avg       0.93      0.94      0.92     37778



In [ ]:
confusion_matrix(y_test,y_pred1)


array([[34084,   156],
       [ 2239,  1299]])

In [ ]:
from sklearn.naive_bayes import BernoulliNB
nb = BernoulliNB()
nb.fit(X_train,y_train)
y_pred3 = nb.predict(X_test)
print("Accuracy : ",accuracy_score(y_test,y_pred3))

Accuracy :  0.9063476097199428


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn import metrics
from sklearn.metrics import r2_score
import numpy as np
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred3))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred3))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred3)))
print('R^2 score is:', r2_score(y_test, y_pred3))
print("Accuracy : ",metrics.accuracy_score(y_test,y_pred3))
print(classification_report(y_test,y_pred3))

Mean Absolute Error: 0.09365239028005717
Mean Squared Error: 0.09365239028005717
Root Mean Squared Error: 0.3060267803314886
R^2 score is: -0.10332943925233629
Accuracy :  0.9063476097199428
              precision    recall  f1-score   support

           0       0.91      1.00      0.95     34240
           1       0.00      0.00      0.00      3538

    accuracy                           0.91     37778
   macro avg       0.45      0.50      0.48     37778
weighted avg       0.82      0.91      0.86     37778



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
confusion_matrix(y_test,y_pred3)


array([[34240,     0],
       [ 3538,     0]])

In [ ]:
from sklearn.svm import SVC
Clf = SVC()
Clf.fit(X_train,y_train)
y_pred4 = Clf.predict(X_test)
print("Accuracy : ",accuracy_score(y_test,y_pred4))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy :  0.9063476097199428


In [ ]:
from sklearn import metrics
from sklearn.metrics import r2_score
import numpy as np
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred4))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred4))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred4)))
print('R^2 score is:', r2_score(y_test, y_pred4))
print("Accuracy : ",metrics.accuracy_score(y_test,y_pred4))
print(classification_report(y_test,y_pred4))

Mean Absolute Error: 0.09365239028005717
Mean Squared Error: 0.09365239028005717
Root Mean Squared Error: 0.3060267803314886
R^2 score is: -0.10332943925233629
Accuracy :  0.9063476097199428
              precision    recall  f1-score   support

           0       0.91      1.00      0.95     34240
           1       0.00      0.00      0.00      3538

    accuracy                           0.91     37778
   macro avg       0.45      0.50      0.48     37778
weighted avg       0.82      0.91      0.86     37778



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
confusion_matrix(y_test,y_pred4)


array([[34240,     0],
       [ 3538,     0]])

# ***Decision tree entropy and gini***

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion='entropy')
clf.fit(X_train,y_train)
y_pred5 = clf.predict(X_test)
print("Accuracy : ",accuracy_score(y_test,y_pred5))

Accuracy :  0.928688654772619


In [ ]:
from sklearn import metrics
from sklearn.metrics import r2_score
import numpy as np
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred5))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred5))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred5)))
print('R^2 score is:', r2_score(y_test, y_pred5))
print("Accuracy : ",metrics.accuracy_score(y_test,y_pred5))
print(classification_report(y_test,y_pred5))

Mean Absolute Error: 0.07131134522738101
Mean Squared Error: 0.07131134522738101
Root Mean Squared Error: 0.26704184171657636
R^2 score is: 0.15987294817812492
Accuracy :  0.928688654772619
              precision    recall  f1-score   support

           0       0.97      0.96      0.96     34240
           1       0.61      0.67      0.64      3538

    accuracy                           0.93     37778
   macro avg       0.79      0.81      0.80     37778
weighted avg       0.93      0.93      0.93     37778



In [ ]:
confusion_matrix(y_test,y_pred5)


array([[32702,  1538],
       [ 1156,  2382]])

In [ ]:
clf = DecisionTreeClassifier(criterion='gini')
clf.fit(X_train,y_train)
y_pred6 = clf.predict(X_test)
print("Accuracy : ",accuracy_score(y_test,y_pred6))
y_pred6

Accuracy :  0.9268357244957383


array([0, 0, 0, ..., 0, 0, 1])

In [ ]:
from sklearn import metrics
from sklearn.metrics import r2_score
import numpy as np
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred6))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred6))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred6)))
print('R^2 score is:', r2_score(y_test, y_pred6))
print("Accuracy : ",metrics.accuracy_score(y_test,y_pred6))
print(classification_report(y_test,y_pred6))

Mean Absolute Error: 0.07316427550426174
Mean Squared Error: 0.07316427550426174
Root Mean Squared Error: 0.2704889563443612
R^2 score is: 0.13804336628223357
Accuracy :  0.9268357244957383
              precision    recall  f1-score   support

           0       0.97      0.95      0.96     34240
           1       0.60      0.68      0.63      3538

    accuracy                           0.93     37778
   macro avg       0.78      0.81      0.80     37778
weighted avg       0.93      0.93      0.93     37778



In [ ]:
confusion_matrix(y_test,y_pred6)


array([[32624,  1616],
       [ 1148,  2390]])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=70, max_leaf_nodes=10, n_jobs=-1,
                                oob_score=True, random_state=42)
rfc.fit(X_train, y_train)
y_pred7 = rfc.predict(X_test)
print("Accuracy : ",accuracy_score(y_test,y_pred7))
y_pred7

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


Accuracy :  0.955847318545185


array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
confusion_matrix(y_test,y_pred7)


array([[34149,    91],
       [ 1577,  1961]])

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)
y_pred9 = dtc.predict(X_test)
y_pred9

array([0, 0, 0, ..., 0, 0, 1])

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
ABC = AdaBoostClassifier(DecisionTreeClassifier(max_depth=1))

ABC.fit(X_train,y_train)
y_pred8 = ABC.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
print("Accuracy : ",accuracy_score(y_test,y_pred8))

Accuracy :  0.948647360897877


In [ ]:
confusion_matrix(y_test,y_pred8)


array([[33616,   624],
       [ 1316,  2222]])

In [ ]:
print("Accuracy : ",accuracy_score(y_test,y_pred9))

Accuracy :  0.9264651384403622


In [ ]:
confusion_matrix(y_test,y_pred9)


array([[32607,  1633],
       [ 1145,  2393]])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1, stratify=y)
clf = RandomForestClassifier(max_samples=0.9,n_estimators=1000,max_features=16)
clf.fit(X_train, y_train)

# Make predictions for the test set
y_pred_test = clf.predict(X_test)

clf.score(X_test, y_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


0.8485626555137911

In [ ]:
confusion_matrix(y_test, y_pred_test)

array([[31813,  2427],
       [ 3294,   244]])

In [ ]:
print('R^2 score is:', r2_score(y_test, y_pred_test))

R^2 score is: -0.784100543234205


In [ ]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.91      0.93      0.92     34240
           1       0.09      0.07      0.08      3538

    accuracy                           0.85     37778
   macro avg       0.50      0.50      0.50     37778
weighted avg       0.83      0.85      0.84     37778



In [ ]:
clf = RandomForestClassifier(max_samples=0.9,n_estimators=1000,max_features=16)
clf.fit(X_train, y_train)
y_pred_rf = clf.predict(X_test)
accuracy_score(y_test, y_pred_rf)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


0.8485361850812643

In [ ]:
 
print('R^2 score is:', r2_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

R^2 score is: -0.7844123944041463
              precision    recall  f1-score   support

           0       0.91      0.93      0.92     34240
           1       0.09      0.07      0.08      3538

    accuracy                           0.85     37778
   macro avg       0.50      0.50      0.50     37778
weighted avg       0.83      0.85      0.84     37778



In [ ]:
confusion_matrix(y_test, y_pred_rf)

array([[31813,  2427],
       [ 3295,   243]])

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=50)
clf.fit(X_train, y_train)
y_pred_ada = clf.predict(X_test)
accuracy_score(y_test, y_pred_ada)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.906321139287416

In [ ]:

print('R^2 score is:', r2_score(y_test, y_pred_ada))
print(classification_report(y_test, y_pred_ada))

R^2 score is: -0.10364129042227788
              precision    recall  f1-score   support

           0       0.91      1.00      0.95     34240
           1       0.00      0.00      0.00      3538

    accuracy                           0.91     37778
   macro avg       0.45      0.50      0.48     37778
weighted avg       0.82      0.91      0.86     37778



In [ ]:
confusion_matrix(y_test, y_pred_ada)

array([[34239,     1],
       [ 3538,     0]])

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
clf = GradientBoostingClassifier(n_estimators=50)
clf.fit(X_train, y_train)
y_pred_gdb = clf.predict(X_test)
accuracy_score(y_test, y_pred_gdb)

/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9063476097199428

In [ ]:

print('R^2 score is:', r2_score(y_test, y_pred_gdb))
print(classification_report(y_test, y_pred_gdb))

R^2 score is: -0.10332943925233651
              precision    recall  f1-score   support

           0       0.91      1.00      0.95     34240
           1       0.00      0.00      0.00      3538

    accuracy                           0.91     37778
   macro avg       0.45      0.50      0.48     37778
weighted avg       0.82      0.91      0.86     37778



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
confusion_matrix(y_test, y_pred_gdb)

array([[34240,     0],
       [ 3538,     0]])

#Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
M1 = LogisticRegression()
M1.fit(X_train,y_train)
y_pred1 = M1.predict(X_test)
print("Accuracy : ",accuracy_score(y_test,y_pred1))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy :  0.9366033140981523


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [ ]:
from sklearn import metrics
from sklearn.metrics import classification_report,r2_score
import numpy as np
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred1))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred1))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred1)))
print('R^2 score is:', r2_score(y_test, y_pred1))
print("Accuracy : ",metrics.accuracy_score(y_test,y_pred1))
print(classification_report(y_test,y_pred1))

Mean Absolute Error: 0.06339668590184763
Mean Squared Error: 0.06339668590184763
Root Mean Squared Error: 0.2517869851716876
R^2 score is: 0.2531164479905751
Accuracy :  0.9366033140981523
              precision    recall  f1-score   support

           0       0.94      1.00      0.97     34240
           1       0.89      0.37      0.52      3538

    accuracy                           0.94     37778
   macro avg       0.92      0.68      0.74     37778
weighted avg       0.93      0.94      0.92     37778



In [ ]:
confusion_matrix(y_test,y_pred1)


array([[34084,   156],
       [ 2239,  1299]])

# ***Naive Bayes***

In [ ]:
from sklearn.naive_bayes import BernoulliNB
nb = BernoulliNB()
nb.fit(X_train,y_train)
y_pred3 = nb.predict(X_test)
print("Accuracy : ",accuracy_score(y_test,y_pred3))

Accuracy :  0.9063476097199428


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn import metrics
from sklearn.metrics import r2_score
import numpy as np
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred3))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred3))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred3)))
print('R^2 score is:', r2_score(y_test, y_pred3))
print("Accuracy : ",metrics.accuracy_score(y_test,y_pred3))
print(classification_report(y_test,y_pred3))

Mean Absolute Error: 0.09365239028005717
Mean Squared Error: 0.09365239028005717
Root Mean Squared Error: 0.3060267803314886
R^2 score is: -0.10332943925233629
Accuracy :  0.9063476097199428
              precision    recall  f1-score   support

           0       0.91      1.00      0.95     34240
           1       0.00      0.00      0.00      3538

    accuracy                           0.91     37778
   macro avg       0.45      0.50      0.48     37778
weighted avg       0.82      0.91      0.86     37778



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
